name: Update JSON

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run update_json.js
        run: |
          npm install
          node preprocessing/update_json.js
        env:
          CI: true

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Updated JSON"
          git push origin master
